# Uncomment the next line to define a global platform for your project
 
platform :ios, '14.0'

target 'SLExtensionKit_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'SLExtensionKit', :path => '../'

end



target 'WidgetExtExtension' do
  
  use_frameworks!
  
  pod 'SLExtensionKit', :path => '../'
  
end


